export const classesData = [
    {
      id: 1,
      name: "1A",
      capacity: 20,
      grade: 1,
      supervisor: "Joseph Padilla",
    },
    {
      id: 2,
      name: "2B",
      capacity: 22,
      grade: 2,
      supervisor: "Blake Joseph",
    },
    {
      id: 3,
      name: "3C",
      capacity: 20,
      grade: 3,
      supervisor: "Tom Bennett",
    },
    {
      id: 4,
      name: "4B",
      capacity: 18,
      grade: 4,
      supervisor: "Aaron Collins",
    },
    {
      id: 5,
      name: "5A",
      capacity: 16,
      grade: 5,
      supervisor: "Iva Frank",
    },
    {
      id: 6,
      name: "5B",
      capacity: 20,
      grade: 5,
      supervisor: "Leila Santos",
    },
    {
      id: 7,
      name: "7A",
      capacity: 18,
      grade: 7,
      supervisor: "Carrie Walton",
    },
    {
      id: 8,
      name: "6B",
      capacity: 22,
      grade: 6,
      supervisor: "Christopher Butler",
    },
    {
      id: 9,
      name: "6C",
      capacity: 18,
      grade: 6,
      supervisor: "Marc Miller",
    },
    {
      id: 10,
      name: "6D",
      capacity: 20,
      grade: 6,
      supervisor: "Ophelia Marsh",
    },
  ];