export const examsData = [
    {
      id: 1,
      subject: "Math",
      class: "1A",
      teacher: "Martha Morris",
      date: "2025-01-01",
    },
    {
      id: 2,
      subject: "English",
      class: "2A",
      teacher: "Randall Garcia",
      date: "2025-01-01",
    },
    {
      id: 3,
      subject: "Science",
      class: "3A",
      teacher: "Myrtie Scott",
      date: "2025-01-01",
    },
    {
      id: 4,
      subject: "Social Studies",
      class: "1B",
      teacher: "Alvin Swanson",
      date: "2025-01-01",
    },
    {
      id: 5,
      subject: "Art",
      class: "4A",
      teacher: "Mabelle Wallace",
      date: "2025-01-01",
    },
    {
      id: 6,
      subject: "Music",
      class: "5A",
      teacher: "Dale Thompson",
      date: "2025-01-01",
    },
    {
      id: 7,
      subject: "History",
      class: "6A",
      teacher: "Allie Conner",
      date: "2025-01-01",
    },
    {
      id: 8,
      subject: "Geography",
      class: "6B",
      teacher: "Hunter Fuller",
      date: "2025-01-01",
    },
    {
      id: 9,
      subject: "Physics",
      class: "7A",
      teacher: "Lois Lindsey",
      date: "2025-01-01",
    },
    {
      id: 10,
      subject: "Chemistry",
      class: "8A",
      teacher: "Vera Soto",
      date: "2025-01-01",
    },
  ];
  