export const resultsData = [
  {
    id: 1,
    CoursSubject: "Math",
    class: "1A",
    teacher: "Alice Johnson",
    student: "Michael Smith",
    date: "2025-02-01",
    type: "exam",
    score: 85,
  },
  {
    id: 2,
    CoursSubject: "English",
    class: "2A",
    teacher: "Sarah Brown",
    student: "Emma Wilson",
    date: "2025-02-02",
    type: "exam",
    score: 78,
  },
  {
    id: 3,
    CoursSubject: "Science",
    class: "3A",
    teacher: "Robert Davis",
    student: "Liam Martinez",
    date: "2025-02-03",
    type: "exam",
    score: 92,
  },
  {
    id: 4,
    CoursSubject: "Social Studies",
    class: "1B",
    teacher: "Jessica Garcia",
    student: "Olivia Taylor",
    date: "2025-02-04",
    type: "exam",
    score: 88,
  },
  {
    id: 5,
    CoursSubject: "Art",
    class: "4A",
    teacher: "David Miller",
    student: "Noah Anderson",
    date: "2025-02-05",
    type: "exam",
    score: 95,
  },
  {
    id: 6,
    CoursSubject: "Music",
    class: "5A",
    teacher: "Linda Martinez",
    student: "Sophia Thomas",
    date: "2025-02-06",
    type: "exam",
    score: 75,
  },
  {
    id: 7,
    CoursSubject: "History",
    class: "6A",
    teacher: "Chris Jackson",
    student: "Aiden White",
    date: "2025-02-07",
    type: "exam",
    score: 89,
  },
  {
    id: 8,
    CoursSubject: "Geography",
    class: "6B",
    teacher: "Nancy Wilson",
    student: "Mia Harris",
    date: "2025-02-08",
    type: "exam",
    score: 83,
  },
  {
    id: 9,
    CoursSubject: "Physics",
    class: "7A",
    teacher: "Mark Young",
    student: "Isabella Lee",
    date: "2025-02-09",
    type: "exam",
    score: 91,
  },
  {
    id: 10,
    CoursSubject: "Chemistry",
    class: "8A",
    teacher: "Patricia Lewis",
    student: "Ethan Walker",
    date: "2025-02-10",
    type: "exam",
    score: 87,
  },
  {
    id: 11,
    CoursSubject: "Biology",
    class: "9A",
    teacher: "James Robinson",
    student: "Charlotte Hall",
    date: "2025-02-11",
    type: "exam",
    score: 82,
  },
  {
    id: 12,
    CoursSubject: "Literature",
    class: "10A",
    teacher: "William Allen",
    student: "Jackson King",
    date: "2025-02-12",
    type: "exam",
    score: 76,
  },
  {
    id: 13,
    CoursSubject: "Philosophy",
    class: "11A",
    teacher: "Barbara Wright",
    student: "Amelia Scott",
    date: "2025-02-13",
    type: "exam",
    score: 90,
  },
  {
    id: 14,
    CoursSubject: "Psychology",
    class: "12A",
    teacher: "Steven Hill",
    student: "Lucas Green",
    date: "2025-02-14",
    type: "exam",
    score: 84,
  },
  {
    id: 15,
    CoursSubject: "Statistics",
    class: "1C",
    teacher: "Daniel Adams",
    student: "Ella Turner",
    date: "2025-02-15",
    type: "exam",
    score: 88,
  },
  {
    id: 16,
    CoursSubject: "Economics",
    class: "2C",
    teacher: "Michelle Perez",
    student: "Ava Martinez",
    date: "2025-02-16",
    type: "exam",
    score: 91,
  },
  {
    id: 17,
    CoursSubject: "Computer Science",
    class: "3B",
    teacher: "Jessica Lopez",
    student: "Liam Baker",
    date: "2025-02-17",
    type: "exam",
    score: 95,
  },
  {
    id: 18,
    CoursSubject: "Physical Education",
    class: "4B",
    teacher: "Jason Clark",
    student: "Oliver Hall",
    date: "2025-02-18",
    type: "exam",
    score: 87,
  },
  {
    id: 19,
    CoursSubject: "Drama",
    class: "5B",
    teacher: "Katherine Allen",
    student: "Chloe Hill",
    date: "2025-02-19",
    type: "exam",
    score: 93,
  },
  {
    id: 20,
    CoursSubject: "French",
    class: "6C",
    teacher: "Ryan Wright",
    student: "Aiden Young",
    date: "2025-02-20",
    type: "exam",
    score: 80,
  },
  {
    id: 21,
    CoursSubject: "Spanish",
    class: "7C",
    teacher: "Rachel Scott",
    student: "Ella Lewis",
    date: "2025-02-21",
    type: "exam",
    score: 89,
  },
  {
    id: 22,
    CoursSubject: "Italian",
    class: "8C",
    teacher: "Michael Hall",
    student: "James Johnson",
    date: "2025-02-22",
    type: "exam",
    score: 77,
  },
  {
    id: 23,
    CoursSubject: "History of Art",
    class: "9B",
    teacher: "Andrew Allen",
    student: "Sophia Martinez",
    date: "2025-02-23",
    type: "exam",
    score: 86,
  },
  {
    id: 24,
    CoursSubject: "Graphic Design",
    class: "10B",
    teacher: "Laura Lee",
    student: "Liam White",
    date: "2025-02-24",
    type: "exam",
    score: 91,
  },
  {
    id: 25,
    CoursSubject: "Music Theory",
    class: "11B",
    teacher: "George Harris",
    student: "Mia Garcia",
    date: "2025-02-25",
    type: "exam",
    score: 90,
  },
  {
    id: 26,
    CoursSubject: "Environmental Science",
    class: "12B",
    teacher: "Betty Walker",
    student: "Noah Brown",
    date: "2025-02-26",
    type: "exam",
    score: 83,
  },
  {
    id: 27,
    CoursSubject: "Business Studies",
    class: "1D",
    teacher: "Jessica Young",
    student: "Charlotte Robinson",
    date: "2025-02-27",
    type: "exam",
    score: 94,
  },
  {
    id: 28,
    CoursSubject: "Astronomy",
    class: "2D",
    teacher: "Tracy Clark",
    student: "Ethan Adams",
    date: "2025-02-28",
    type: "exam",
    score: 88,
  },
  {
    id: 29,
    CoursSubject: "Sociology",
    class: "3C",
    teacher: "Samuel Thompson",
    student: "Sophie Lewis",
    date: "2025-03-01",
    type: "exam",
    score: 81,
  },
  {
    id: 30,
    CoursSubject: "Statistics",
    class: "4C",
    teacher: "Nancy Harris",
    student: "Oliver Green",
    date: "2025-03-02",
    type: "exam",
    score: 90,
  },
  {
    id: 31,
    CoursSubject: "English",
    class: "2A",
    teacher: "Sarah Brown",
    student: "Emma Wilson",
    date: "2025-02-02",
    type: "exam",
    score: 78,
  },
];
